nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  postcss-scss@*:
    peerDependenciesMeta:
      postcss:
        optional: true

yarnPath: .yarn/releases/yarn-3.6.2.cjs
